### PR TITLE
Introduce test/lint GitHub Actions workflow

### PR DESCRIPTION
**Pull request by never147**
This PR adds a workflow that runs PSScriptAnalyzer and Pester. 

The lint checker PSScriptAnalyzer has been configured to ignore some false-positive warnings. I have applied a number of "fixes" that seemed trivial but I might not have done the right thing in all cases. The script appears to run ok. 

There are some outstanding errors and warnings. See https://github.com/never147/Diablo2RLoader/actions/runs/6841690812/job/18602333172

You can see the first run which lists "3 errors and 488 warnings total", https://github.com/never147/Diablo2RLoader/actions/runs/6840734020/job/18600323123 

There are no unit tests as yet for Pester so it exits with success until those are written. Docs for Pester are at https://pester.dev/docs/quick-start

### CODE REVIEW

**Comment by shupershuff** [comment]
Hi there,
Thanks for the PR but I must admit I'm not familiar with PSScriptAnalyzer or Pester, are you able to explain this and the purpose of the PR?

**Comment by never147** [comment]
Hi @shupershuff !

No probs. I'm not sure how familiar you are with testing in software development but PSScriptAnalyzer is a code linter, which tells you about possible know coding problems and conventions, and Pester is for unit testing, which is where you write code that will test specific parts of your code. The other part is the GitHub workflow which (when merged) will run each of those 2 programs on the main branch when code is pushed and on branches when pull-requests are created/updated.

I noticed a some warnings and a few errors when I was looking at the code and thought to give something back. I hope that this might help people who contribute to this project by giving them tools to improve code quality and give early warnings of problems in the code. I think the code is already really good and this is something I do in my day job so wanted to contribute.

I guess next steps would be to write some tests that interact with individual functions in the script to ensure they operate as expected. I don't expect you to do this if you do not wish to, but if you are interested in software development you might want to take a look. A good starting point is writing regression tests (to check that bugs remain fixed).

Let me know if you have any more questions or thoughts.

**Comment by shupershuff** [comment]
Certainly keen to expand my knowledge here and apply some good practices around it.
I think there's a few good practice improvements and tidy ups identified from the first run you did.
For the second run, I can't say I can resolve any of those warnings or errors (at least not with my current knowledge).
But always happy to take feedback/criticism and make improvements where possible.

For Pester, I can't promise that I'll be able to commit to writing tests as it would be a huge amount of work. 
Although it would definitely be awesome to validate data is being passed through variables as expected, especially as some of the external services/API's this script relies on may change or become defunct.
You wouldn't believe how many things and how many times I've tested the data in various variables during development and again prior to releases :)

**Comment by shupershuff** [comment]
Can the workflow/test files introduced reside in another folder (eg the .github directory) or do they need to sit in the root directory?

**Comment by never147** [comment]
> Certainly keen to expand my knowledge here and apply some good practices around it. I think there's a few good practice improvements and tidy ups identified from the first run you did. For the second run, I can't say I can resolve any of those warnings or errors (at least not with my current knowledge). But always happy to take feedback/criticism and make improvements where possible.

I got to the same point, I wasn't sure how to fix so left it to see if you had an idea. So we can either attempt to fix those issues now or we can set an exclusion in rules for that part of the code, either at the function level or in the settings file. I'll take a look at that. One thing I do then is create a ticket to keep record and come back to it. As one is a security issue it might be worth doing that. I'll take a look first to see if I can find out what it means first.

> For Pester, I can't promise that I'll be able to commit to writing tests as it would be a huge amount of work. Although it would definitely be awesome to validate data is being passed through variables as expected, especially as some of the external services/API's this script relies on may change or become defunct. You wouldn't believe how many things and how many times I've tested the data in various variables during development and again prior to releases :)

That's exactly what it's for. It can be really useful for doing tests to be able to confirm a release is ready. Pester doesn't need any tests right now but I could certainly help with that. Maybe you could define the expected inputs in a config file like JSON/YAML and write some code that calls the functions that use the APIs. The test framework would run each of those and validate the success (or failure in case you want to confirm that it fails when expected too).

> > I'm not sure how familiar you are with testing in software development
> 
> Oh and just for your context, whilst interested, I have practically no background or experience in Software Development. Formally I work in a non-technical role but have historically used PowerShell for performing exports from M365 etc and have written a few basic PS scripts. As you've noticed I'm clearly new to using GitHub too :) Currently I just write stuff in Notepad++, test it and then edit the main branch here once I'm happy. I suspect that's not the best way of doing things either.

Tbh I think what you've done is awesome. I've been using VSCode as it has plugins for PSScriptAnalyzer.

**Comment by never147** [comment]
> Can the workflow/test files introduced reside in another folder (eg the .github directory) or do they need to sit in the root directory? The reason I ask is it may look a little less overwhelming/scary for end users having a look at the source files.

Yes definitely. It might be worth having the test files under a "tests" directory. I'll take a look at that. The '.gitignore' file needs to live in the root.

> Also keen to know if both the PSScriptAnalyser workflow and pester is automatic or initiated on an ad hoc basis?

The workflow is triggered according to these events https://github.com/shupershuff/Diablo2RLoader/pull/30/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R3-R10
They mean, whenever someone pushes to a branch which part of a PR targeting the "main" branch, whenever someone pushes to the "main" branch and the `workflow_dispatch` is a manual trigger. When this is merged and the workflow file exists on the "main" branch then you'll see the workflow under the actions tab on the project, it will have a "run workflow" button then and you can specify the branch you want to run the workflow with.
The job will checkout the branch that the workflow runs on in 2 separate environments, in parallel, and run each test.

**Comment by never147** [comment]
I've moved some of the test files and added rule exclusions for the problems that cannot be fixed at the moment. See a successful test run here https://github.com/never147/Diablo2RLoader/actions/runs/6909051721

**Comment by shupershuff** [comment]
> I've moved some of the test files and added rule exclusions for the problems that cannot be fixed at the moment. See a successful test run here https://github.com/never147/Diablo2RLoader/actions/runs/6909051721

Thanks for this. I have a small, unexciting updated planned which can test out these new features but I'm about to travel overseas for a couple of weeks so it might be a while until I get to it.

**Comment by never147** [comment]
> > I've moved some of the test files and added rule exclusions for the problems that cannot be fixed at the moment. See a successful test run here https://github.com/never147/Diablo2RLoader/actions/runs/6909051721
> 
> Thanks for this. I have a small, unexciting updated planned which can test out these new features but I'm about to travel overseas for a couple of weeks so it might be a while until I get to it.

Whoop! Thanks! The first run was successful https://github.com/shupershuff/Diablo2RLoader/actions/runs/6963651918

**Pull request merged**
